# Generated by Django 5.1.1 on 2024-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
