# Generated by Django 4.2.15 on 2024-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='未知', max_length=255)),
                ('cost', models.CharField(default='未知', max_length=10)),
            ],
        ),
    ]
